### ISSUE TITLE
Failed to join room due to Daily.CallClientError and fatal runtime error

### ISSUE THREAD

**Issue by blain-vpm** [daily-co/daily-client-ios#13]
**Description**:
When joining a room, if it fails there's a fatal crash.

**Steps to reproduce:**
Attempt to join a room in the Daily SDK.
Receive the error: The operation couldn’t be completed. (Daily.CallClientError error 0.)
The following Rust runtime error also occurs: fatal runtime error: Rust cannot catch foreign exceptions.

**Expected behaviour:**
The SDK should join the room or give an appropriate error message if the client is already in a call.

**Actual behaviour:**
The SDK throws a Daily.CallClientError and terminates with a fatal Rust error.

**Error Logs:**
```
2024-10-15T15:05:40+0100 error com.voxpopme.DailyScreenShareViewController : [] Failed to join room:
Description: The operation couldn’t be completed. (Daily.CallClientError error 0.)
Code: 0
Domain: Daily.CallClientError
User Info: [:]
Analytics event: Join Failed, params: ["error": "The operation couldn’t be completed. (Daily.CallClientError error 0.)", "errorDomain": "Daily.CallClientError", "errorCode": "0", "userInfo": "[:]", "roomUrl": "t-*****"]
2024-10-15T15:05:40+0100 info com.voxpopme.DailyScreenShareViewController : Inputs updated: screenVideo=ScreenVideoInputSettings(isEnabled: false)

fatal runtime error: Rust cannot catch foreign exceptions
```
Environment:

SDK version: 0.24.0
Device/OS: iPhone 14 Pro, iOS 17.6.1

**Comment by filipi87** [comment]
Hi @blain-vpm, thanks for reporting this.

Just based on your previous description, we have not been able to reproduce it. 

Couple of questions:
- Is it happening every time or sporadically ?
- Are you able to reproduce it using one of our demos ?
  - https://github.com/daily-demos/daily-ios-demo
  - https://github.com/daily-demos/daily-ios-starter-kit

If you continue to experience this issue, please provide:
- A complete code snippet to help us replicate the issue. Or the steps that we need to follow in one of our demos to reproduce it.
- The full log.

This information will help us assist you more effectively.

**Comment by blain-vpm** [comment]
Hi,

I’ve identified that the `fatal runtime error: Rust cannot catch foreign exceptions` crash was happening when the client was already in a room and attempted to join another one. However, I can no longer replicate the crash. Has there been any recent update on your backend that might have resolved that issue?

Thanks!

**Comment by filipi87** [comment]
Hi @blain-vpm,

There have been a couple of updates to our backend, but none specifically aimed at fixing this issue.

If you're able to reproduce it again, please provide a code snippet or detailed steps we can follow to replicate it in one of our demos, along with the full log.

I'll keep this open for a few more days while we attempt to replicate it as well.

Thank you!
